description: 3DS Injector

patches:
    3ds_injector.cxi:
        type: Sysmodule
        subtype: NATIVE_FIRM
        versions:
            n3ds:
                0x2F: 0
                0x2D: 0
                0x28: 0
                0x26: 0
                0x21: 0
                0x1F: 0
                0x1B: 0
                0x1A: 0
                0x18: 0
                0x0F: 0
                0x0B: 0
                0x04: 0
                0x03: 0
            o3ds:
                0x5E: 0
                0x5C: 0
                0x58: 0
                0x56: 0
                0x52: 0
                0x50: 0
                0x4C: 0
                0x4B: 0
                0x49: 0
                0x40: 0
                0x3F: 0
                0x38: 0
                0x37: 0
                0x30: 0
                0x2E: 0
                0x2A: 0
                0x29: 0
                0x26: 0
                0x25: 0
                0x1F: 0
                0x1D: 0
                0x18: 0
                0x0F: 0
                0x0B: 0
                0x09: 0
                0x02: 0
                0x00: 0
